import { z } from 'zod';
import type { Nutrients } from './nutrients';

/**
 * Accepts only an https origin (optionally with a trailing slash). Returns the normalized origin
 * or null. Paths, query strings and credentials are rejected so the token can't leak elsewhere.
 */
export function normalizeServerUrl(raw: string): string | null {
  const s = raw.trim();
  if (!s || s.length > 200) return null;
  let url: URL;
  try {
    url = new URL(s);
  } catch {
    return null;
  }
  if (url.protocol !== 'https:') return null;
  if (url.username || url.password || url.search || url.hash) return null;
  if (url.pathname !== '/' && url.pathname !== '') return null;
  if (!/^[a-z0-9.-]+$/i.test(url.hostname) || !url.hostname.includes('.')) return null;
  return url.origin;
}

/** Device tokens are generated by the server's gen-token script: 43 base64url characters (32 bytes). */
export function isValidDeviceToken(t: string): boolean {
  return /^[A-Za-z0-9_-]{32,128}$/.test(t);
}

const text = (max: number) =>
  z
    .string()
    .max(max * 4)
    .transform((s) => s.replace(/[\u0000-\u001f\u007f<>]/g, '').trim().slice(0, max));
const num = (max: number) => z.number().finite().min(0).max(max);

const macro100 = num(100).nullable();
const aiPer100gSchema = z
  .object({
    energy_kcal: num(900),
    protein_g: macro100,
    carbs_g: macro100,
    fat_g: macro100,
    fiber_g: macro100,
    sugars_g: macro100,
    sat_fat_g: macro100,
    sodium_mg: num(40_000).nullable(),
  })
  .refine((v) => (v.protein_g ?? 0) + (v.carbs_g ?? 0) + (v.fat_g ?? 0) <= 100);

export const aiItemSchema = z.object({
  name_en: text(120),
  name_de: text(120),
  quantity: num(10_000),
  unit: text(20),
  grams_estimate: num(5_000).nullable(),
  confidence: z.enum(['high', 'medium', 'low']),
  per_100g: aiPer100gSchema.nullable().optional().catch(null),
});
export type AiItem = z.infer<typeof aiItemSchema>;

/** The AI's own per-100 g estimate as app nutrients, or null if it gave none. */
export function aiEstimatePer100g(item: AiItem): Nutrients | null {
  const e = item.per_100g;
  if (!e) return null;
  const out: Nutrients = { energy: e.energy_kcal };
  const set = (k: keyof Nutrients, v: number | null) => {
    if (v !== null) out[k] = v;
  };
  set('protein', e.protein_g);
  set('carbs', e.carbs_g);
  set('fat', e.fat_g);
  set('fiber', e.fiber_g);
  set('sugars', e.sugars_g);
  set('satFat', e.sat_fat_g);
  set('sodium', e.sodium_mg);
  return out;
}
export const itemsResponseSchema = z.object({ items: z.array(aiItemSchema).max(20) });

const per100 = num(1_000).nullable();
export const labelResponseSchema = z.object({
  label: z
    .object({
      name: text(120).nullable(),
      brand: text(120).nullable(),
      basis: z.enum(['100g', '100ml', 'serving']),
      serving_grams: num(5_000).nullable(),
      energy_kcal: per100,
      protein_g: per100,
      carbs_g: per100,
      sugars_g: per100,
      fat_g: per100,
      sat_fat_g: per100,
      fiber_g: per100,
      salt_g: per100,
      sodium_mg: num(100_000).nullable(),
    })
    .nullable(),
});
export type AiLabel = NonNullable<z.infer<typeof labelResponseSchema>['label']>;

export const insightsResponseSchema = z.object({
  insights: z
    .array(z.object({ title: text(80), body: text(400), kind: z.enum(['gap', 'excess', 'positive', 'tip']) }))
    .max(5),
});
export type AiInsight = z.infer<typeof insightsResponseSchema>['insights'][number];

/**
 * Converts label values to per-100 g. Returns null if the basis is per serving without a
 * serving size (can't convert). "100ml" is treated as 100 g (close enough for most drinks).
 */
export function labelToPer100g(l: AiLabel): Nutrients | null {
  let factor = 1;
  if (l.basis === 'serving') {
    if (!l.serving_grams || l.serving_grams <= 0) return null;
    factor = 100 / l.serving_grams;
  }
  const out: Nutrients = {};
  const set = (k: keyof Nutrients, v: number | null, scale = 1) => {
    if (v !== null) out[k] = v * factor * scale;
  };
  set('energy', l.energy_kcal);
  set('protein', l.protein_g);
  set('carbs', l.carbs_g);
  set('sugars', l.sugars_g);
  set('fat', l.fat_g);
  set('satFat', l.sat_fat_g);
  set('fiber', l.fiber_g);
  if (l.sodium_mg !== null) set('sodium', l.sodium_mg);
  else if (l.salt_g !== null) set('sodium', l.salt_g, 400); // EU labels list salt; sodium = salt / 2.5
  if (out.energy === undefined) return null;
  // Per-100 g values above 100 g of a macro or 900 kcal are physically impossible.
  if (out.energy > 900 || (['protein', 'carbs', 'fat'] as const).some((k) => (out[k] ?? 0) > 100)) return null;
  return out;
}
